# Generated by Django 4.2.4 on 2023-08-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='relation',
            new_name='category',
        ),
    ]
